[build-system]
requires = [
"numpy>=1.21.0",
"pandas>=1.3.0",
"matplotlib>=3.4.2",
"scipy>=1.7.0",
"pillow>=6.2.0",
"kiwisolver>=1.0.1",
"python-dateutil>=2.7",
"cycler>=0.10",
"pyparsing>=2.2.1",
"six>=1.16.0",
"pytz>=2017.3",
"statsmodels>=0.12.2",
"pytest>=6.2.4",
"cython>=0.29.24",
"setuptools>=42",
"wheel"]

build-backend = "setuptools.build_meta"